#!/bin/sh

# Environment variables:
# HUDSON_HOME (required)
# JAVA_HOME (required)
# HUDSON_OPTS (optional)
# JAVA_OPTS (optional)

HUDSON_WAR=${HUDSON_HOME}/hudson.war
HUDSON_LOG=${HUDSON_HOME}/hudson.log
JAVA=${JAVA_HOME}/bin/java
nohup ${JAVA} ${JAVA_OPTS} -jar ${HUDSON_WAR} ${HUDSON_OPTS} > ${HUDSON_LOG} 2>&1 &
